- FemtoDream : Adds TOF Mass Cut facility to study Sideband correlation
alisw/AliPhysics pull request #15473
Opened 2020-09-10 23:49 UTC by sbhawani

2020-09-10 23:50 UTC, alibuild commented
5812826c9ce70736a48e942c19bfb7ad59c91495: approval required: 1 of @bhohlweger (Bernhard Hohlweger), @a-mathis (Andreas Michael Mathis), @qgp (Jochen Klein), @shahor02 (Ruben Shahoyan), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @chiarazampolli (Chiara Zampolli), @otonvd (Oton Vazquez Doce), @davidrohr (David Rohr), @sartozza (Valentina Mantovani Sarti); 1 of @bhohlweger (Bernhard Hohlweger), @a-mathis (Andreas Michael Mathis), @loizides (Constantinos Loizides), @chiarazampolli (Chiara Zampolli), @dongjokim (Dong Jo Kim), @vvislavi (Vytautas Vislavicius), @qgp (Jochen Klein), @yzhouCERN (You Zhou), @majanik (Malgorzata Anna Janik), @pkarczma (Przemyslaw Karczmarczyk), @altsybee (Igor Altsybeev), @dcaffarr (Davide Caffarri), @pchrista (Panos Christakoglou), @KonstantinMikhaylov (Konstantin Mikhaylov), @shahor02 (Ruben Shahoyan), @otonvd (Oton Vazquez Doce), @atimmins (Anthony Robert Timmins), @davidrohr (David Rohr), @zumoravc (Zuzana Moravcova), @jniedzie (Jeremi Niedziela), @marslandALICE (Mesut Arslandok), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @aohlson (Alice Ohlson), @lgraczykCern (Lukasz Kamil Graczykowski), @sartozza (Valentina Mantovani Sarti)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/15473) and comment at the bottom of the page.**_

2020-09-11 07:53 UTC, sartozza requested changes

2020-09-11 07:53 UTC, sartozza commented on PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx
> +      fInvMassCutSBup(0),
please put fInvTOFMass... in all names in order to understand is related to TOF.

2020-09-11 07:53 UTC, sartozza commented on PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx
> +      fInvMassCutSBup(cuts.fInvMassCutSBup),
Put TOF in the name

2020-09-11 07:53 UTC, sartozza commented on PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackHist.h
> +  AliFemtoDreamTrackHist(bool DCADist, bool CombSig, bool TOFM,bool TOFMSq, float pTmin = 0.5, float pTmax = 4.05,  int MultRangeLow = 27, int MultRangeHigh = 55);
Here please put the bool TOFMSq as last argument and put it to false, for backward compatibility

2020-09-11 07:53 UTC, sartozza commented on PWGCF/FEMTOSCOPY/FemtoDream/AliFemtoDreamTrackCuts.cxx
> +bool AliFemtoDreamTrackCuts::TOFMassCuts(AliFemtoDreamTrack *Track) {
The function implemented like this makes the PID part very messy.
So we propose as a solution to include this invariant mass TOF cut inside the PIDCuts function.
Please do this by inserting an option (enumerator or bool) to select whether to use TOFnSigma or InvMassTOF.
You can then re-use your function TOFMassCuts and put the lines of the code around lines 545, so where we have the TOF PID part.

2020-09-11 12:09 UTC, alibuild commented
cb1e55122598611e864e80faba000b76f382154c: approval required: 1 of @bhohlweger (Bernhard Hohlweger), @a-mathis (Andreas Michael Mathis), @qgp (Jochen Klein), @shahor02 (Ruben Shahoyan), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @chiarazampolli (Chiara Zampolli), @otonvd (Oton Vazquez Doce), @davidrohr (David Rohr), @sartozza (Valentina Mantovani Sarti); 1 of @bhohlweger (Bernhard Hohlweger), @a-mathis (Andreas Michael Mathis), @loizides (Constantinos Loizides), @chiarazampolli (Chiara Zampolli), @dongjokim (Dong Jo Kim), @vvislavi (Vytautas Vislavicius), @qgp (Jochen Klein), @yzhouCERN (You Zhou), @majanik (Malgorzata Anna Janik), @pkarczma (Przemyslaw Karczmarczyk), @altsybee (Igor Altsybeev), @dcaffarr (Davide Caffarri), @pchrista (Panos Christakoglou), @KonstantinMikhaylov (Konstantin Mikhaylov), @shahor02 (Ruben Shahoyan), @otonvd (Oton Vazquez Doce), @atimmins (Anthony Robert Timmins), @davidrohr (David Rohr), @zumoravc (Zuzana Moravcova), @jniedzie (Jeremi Niedziela), @marslandALICE (Mesut Arslandok), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @aohlson (Alice Ohlson), @lgraczykCern (Lukasz Kamil Graczykowski), @sartozza (Valentina Mantovani Sarti); 1 of @FriederikeBock (Friederike Bock), @qgp (Jochen Klein), @shahor02 (Ruben Shahoyan), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @nschmidtALICE (Nicolas Vincent Schmidt), @chiarazampolli (Chiara Zampolli), @dmuhlhei (Daniel Michael Muhlheim), @davidrohr (David Rohr)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/15473) and comment at the bottom of the page.**_

2020-09-11 12:36 UTC, dmuhlhei requested changes
Are the changes in AddTask_GammaConvV1 really intended?

2020-09-11 12:56 UTC, sbhawani commented
Dear all,

This is a mistake, I am fixing. The changes in AddTask_GammaConvV1 are not
intentional. Please *do not *approve!
Apologies for inconvenience!


On Fri, Sep 11, 2020 at 2:36 PM dmuhlhei <notifications@github.com> wrote:

> *@dmuhlhei* requested changes on this pull request.
>
> Are the changes in AddTask_GammaConvV1 really intended?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/alisw/AliPhysics/pull/15473#pullrequestreview-486765990>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMSOJJWDIP5KDQJILTHWOQ3SFIKVNANCNFSM4RGEHPMQ>
> .
>

2020-09-11 13:27 UTC, closed without merging