AliAnalysisTaskHFJetIPQA:: consider all final state V0 daughter parti…
alisw/AliPhysics pull request #15772
Opened 2020-10-08 13:30 UTC by kagarner

…cles for max. IP estimation

2020-10-08 13:30 UTC, alibuild commented
0c06f483e7920dcd29a40bcd863a527d1fce1895: approval required: 1 of @rhaake (Rudiger Haake), @qgp (Jochen Klein), @shahor02 (Ruben Shahoyan), @loizides (Constantinos Loizides), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @chiarazampolli (Chiara Zampolli), @raymondEhlers (Raymond James Ehlers), @matplo (Mateusz Ploskon), @mfasDa (Markus Fasel), @lcunquei (Leticia Cunqueiro Mendez), @davidrohr (David Rohr), @adriansev (Adrian Sevcenco), @dcaffarr (Davide Caffarri), @vkucera (Vit Kucera)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/15772) and comment at the bottom of the page.**_

2020-10-08 16:36 UTC, mfasDa requested changes
Never rely on "using namespace std" in header files. This is super dangerous!

2020-10-08 16:36 UTC, mfasDa commented on PWGJE/FlavourJetTasks/AliAnalysisTaskHFJetIPQA.h
> +    Int_t NDaughterInCone(vector<Int_t>& vecDaughLabels, const AliEmcalJet* jet, const AliAODEvent* event, Double_t dRMax, Double_t& ipsig);
Please replace all remaining occurrences of vector with std::vector. The "using namespace std" comes in implicitly from AliJetShapes.h and will be removed in the near future - it is super dangerous.

2020-10-09 12:42 UTC, alibuild commented
5acc456cd4fce13db3b86ebe3a5fb2792818d879: approval required: 1 of @vkucera (Vit Kucera), @rhaake (Rudiger Haake), @adriansev (Adrian Sevcenco), @qgp (Jochen Klein), @matplo (Mateusz Ploskon), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @shahor02 (Ruben Shahoyan), @davidrohr (David Rohr), @dcaffarr (Davide Caffarri), @mfasDa (Markus Fasel), @raymondEhlers (Raymond James Ehlers), @loizides (Constantinos Loizides), @chiarazampolli (Chiara Zampolli), @lcunquei (Leticia Cunqueiro Mendez)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/15772) and comment at the bottom of the page.**_

2020-10-12 12:09 UTC, lcunquei commented
+1

2020-10-12 12:09 UTC, alibuild commented
5acc456cd4fce13db3b86ebe3a5fb2792818d879: approved: will be automatically merged on successful tests

2020-10-12 12:13 UTC, merged