PWGGA/GammaConv: GammaIsoTree fix in MC header selection + fix of neg…
alisw/AliPhysics pull request #15796
Opened 2020-10-12 00:53 UTC by fjonasALICE

… weights

2020-10-12 00:53 UTC, alibuild commented
b5df24b22ee2e43a3f4caf057c7ad1a29426f555: approval required: 1 of @FriederikeBock (Friederike Bock), @qgp (Jochen Klein), @dmuhlhei (Daniel Michael Muhlheim), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @shahor02 (Ruben Shahoyan), @davidrohr (David Rohr), @chiarazampolli (Chiara Zampolli), @nschmidtALICE (Nicolas Vincent Schmidt)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/15796) and comment at the bottom of the page.**_

2020-10-12 07:45 UTC, dmuhlhei requested changes

2020-10-12 07:45 UTC, dmuhlhei commented on PWGGA/GammaConvBase/AliConvEventCuts.cxx
> +          cout << "accepted:" << index << "\t header " << GeneratorName.Data() << endl;
please comment the cout

2020-10-12 22:07 UTC, alibuild commented
1af4be7f0c827b23c406053b9f1ba8e748172552: approval required: 1 of @FriederikeBock (Friederike Bock), @qgp (Jochen Klein), @dmuhlhei (Daniel Michael Muhlheim), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @shahor02 (Ruben Shahoyan), @davidrohr (David Rohr), @chiarazampolli (Chiara Zampolli), @nschmidtALICE (Nicolas Vincent Schmidt)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/15796) and comment at the bottom of the page.**_

2020-10-12 22:09 UTC, fjonasALICE commented on PWGGA/GammaConvBase/AliConvEventCuts.cxx
> +          cout << "accepted:" << index << "\t header " << GeneratorName.Data() << endl;
sorry, missed that! Fixed

2020-10-13 07:40 UTC, dmuhlhei commented
+1

2020-10-13 07:40 UTC, alibuild commented
1af4be7f0c827b23c406053b9f1ba8e748172552: approved: will be automatically merged on successful tests

2020-10-13 07:44 UTC, merged