PWGGA/GammaConv: Remove superflous fMinRDC member
alisw/AliPhysics pull request #15804
Opened 2020-10-12 13:50 UTC by sstiefel19

from AliConversionPhotonCuts

2020-10-12 13:50 UTC, alibuild commented
22f63bba790228f26262ec45587f2a49053dccf1: approval required: 1 of @FriederikeBock (Friederike Bock), @qgp (Jochen Klein), @dmuhlhei (Daniel Michael Muhlheim), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @shahor02 (Ruben Shahoyan), @davidrohr (David Rohr), @chiarazampolli (Chiara Zampolli), @nschmidtALICE (Nicolas Vincent Schmidt)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/15804) and comment at the bottom of the page.**_

2020-10-12 14:17 UTC, dmuhlhei requested changes

2020-10-12 14:17 UTC, dmuhlhei commented on PWGGA/GammaConvBase/AliConversionPhotonCuts.h
> -    Double_t          fMinRDC;                              ///< Min R for Double Counting Cut
please increase classdef

2020-10-12 14:31 UTC, alibuild commented
1d8a784f49b85ac09303a08dc75ccc070579596e: approval required: 1 of @FriederikeBock (Friederike Bock), @qgp (Jochen Klein), @dmuhlhei (Daniel Michael Muhlheim), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @shahor02 (Ruben Shahoyan), @davidrohr (David Rohr), @chiarazampolli (Chiara Zampolli), @nschmidtALICE (Nicolas Vincent Schmidt)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/15804) and comment at the bottom of the page.**_

2020-10-14 07:45 UTC, sstiefel19 commented on PWGGA/GammaConvBase/AliConversionPhotonCuts.h
> -    Double_t          fMinRDC;                              ///< Min R for Double Counting Cut
done

2020-10-14 08:59 UTC, dmuhlhei commented
+1

2020-10-14 08:59 UTC, alibuild commented
1d8a784f49b85ac09303a08dc75ccc070579596e: approved: will be automatically merged on successful tests

2020-10-14 10:40 UTC, merged