[WIP] Adapt EMCAL trigger table to STU format in run3
alisw/AliPhysics pull request #18416
Opened 2021-08-31 19:52 UTC by mfasDa

- Only 2 columns (FastOR ID and ADC)
- All FastOR ADCs only for fraction of events (settable)
- FastOR ADCs from the 3 leading patches for the other events

2021-08-31 19:53 UTC, alibuild commented
440fb5849fce92daa1114bb19f18a04d592ef0c6: approval required: 1 of @mpuccio (Maximiliano Puccio), @qgp (Jochen Klein), @davidrohr (David Rohr), @shahor02 (Ruben Shahoyan), @jgrosseo (Jan Fiete Grosse-Oetringhaus)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/18416) and comment at the bottom of the page.**_

2021-08-31 19:53 UTC, mfasDa commented
Work in progress - don't merge yet!

2021-09-01 18:41 UTC, alibuild commented
33049b0ce13b38b6fc5e9cf534158793c3e27853: approval required: 1 of @mpuccio (Maximiliano Puccio), @qgp (Jochen Klein), @davidrohr (David Rohr), @shahor02 (Ruben Shahoyan), @jgrosseo (Jan Fiete Grosse-Oetringhaus)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/18416) and comment at the bottom of the page.**_

2021-09-01 18:41 UTC, mfasDa commented
Test could be launched.

2021-09-08 10:26 UTC, jgrosseo requested changes
(copied from mail exchange) Your PR makes a new table for the emcal trigger, but we agreed to have both in the same table, didn't we? Wouldn't it be better you adjust the calotrigger table as suggested by Dimitri and keep the filling there?

2021-09-08 15:13 UTC, closed without merging

2021-09-08 15:13 UTC, jgrosseo commented
Needs merging with phos changes first

2021-09-08 15:16 UTC, mfasDa commented
There was no reason to close this pull request!

Indeed as I mentioned in the private discussion the developments from PHOS and EMCAL are parallel and therefore conflicting, however I would have rebased the branch and update the PR once the PHOS changes are merged. Also therefore the PR was marked as [WIP].

Please for the future keep the pull requests open!