Improved output handelling
alisw/AliPhysics pull request #18869
Opened 2021-11-04 16:31 UTC by JColburn-CERN

Removed the Majority of Histograms and simplified the Trees. The idea behind this is that TTrees will be used primarily for analysis in future in order to help with performing offline Analysis. Additionally, This should reduce the size of the output and memory usage to help with train outputs.

	# On branch master
	# Your branch is up to date with 'upstream/master'.

2021-11-04 16:32 UTC, alibuild commented
c3db24fc9be58067206040afe6892d93b0ef4d34: approval required: 1 of @raymondEhlers (Raymond James Ehlers), @matplo (Mateusz Ploskon), @loizides (Constantinos Loizides), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @vkucera (Vit Kucera), @davidrohr (David Rohr), @mfasDa (Markus Fasel), @lcunquei (Leticia Cunqueiro Mendez), @adriansev (Adrian Sevcenco), @shahor02 (Ruben Shahoyan), @qgp (Jochen Klein)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/18869) and comment at the bottom of the page.**_

2021-11-10 14:54 UTC, raymondEhlers requested changes
Hi Sammy, you need to go back and check this commit carefully. You've renamed the class in `AliAnalysisTaskJetCharge.{cxx,h}` to `AliAnalysisTaskJetChargeFlavourTemplate`, but you already define that class in `AliAnalysisTaskJetChargeFlavourTemplate.{cxx,h}`. At best, this is going to lead to unexpected behavior, if it even complies. Please check what you want to do and revise as appropriate

2021-11-10 15:30 UTC, alibuild commented
ab0916b5a72753d5692b19ad60609dbeca0b6021: approval required: 1 of @raymondEhlers (Raymond James Ehlers), @matplo (Mateusz Ploskon), @loizides (Constantinos Loizides), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @vkucera (Vit Kucera), @davidrohr (David Rohr), @mfasDa (Markus Fasel), @lcunquei (Leticia Cunqueiro Mendez), @adriansev (Adrian Sevcenco), @shahor02 (Ruben Shahoyan), @qgp (Jochen Klein)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/18869) and comment at the bottom of the page.**_

2021-11-10 15:31 UTC, JColburn-CERN commented
Hi Raymond, Thanks for pointing this out to me that would have led to some very annoying behaviour had it complied. The issue should be fixed now. Cheers

2021-11-10 15:39 UTC, raymondEhlers requested changes
You don't need to change the jet iterator, but you need to bump the classdef in your flavour task

2021-11-10 15:39 UTC, raymondEhlers commented on PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.cxx
>      while((Jet1=JetCont->GetNextAcceptJet())) {
I guess this was already here, but be aware this is basically a deprecated way of accessing the jets. Preferred is:

```c++
for (auto Jet1 : JetCont->accepted()) {
  // ...
}
```

2021-11-10 15:39 UTC, raymondEhlers commented on PWGJE/EMCALJetTasks/AliAnalysisTaskJetChargeFlavourTemplates.h
>    TChain                              *pChain;                                                     //
Need to bump the ClassDef here

2021-11-11 09:46 UTC, alibuild commented
995afabc8d3ed2028f8b9905ac3061ab00efbea5: approval required: 1 of @raymondEhlers (Raymond James Ehlers), @matplo (Mateusz Ploskon), @loizides (Constantinos Loizides), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @vkucera (Vit Kucera), @davidrohr (David Rohr), @mfasDa (Markus Fasel), @lcunquei (Leticia Cunqueiro Mendez), @adriansev (Adrian Sevcenco), @shahor02 (Ruben Shahoyan), @qgp (Jochen Klein)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/18869) and comment at the bottom of the page.**_

2021-11-11 09:53 UTC, JColburn-CERN commented
Thanks for the help. That classdef dump always gets me.
Your correct that the way of looping through the jets was always there, it's not surprising it's deprecated since the original code I learnt it from was back in root 5. Updated it now to the new preferred method

2021-11-11 10:03 UTC, raymondEhlers commented on PWGJE/EMCALJetTasks/AliAnalysisTaskJetCharge.cxx
>      while((Jet1=JetCont->GetNextAcceptJet())) {
You need to remove the `ResetCurrentID` part too. This can some issues in some causes, which is part of why it was deprecated

2021-11-11 10:17 UTC, alibuild commented
2c012ba920effc67d7cd55fb288bb86851db2862: approval required: 1 of @raymondEhlers (Raymond James Ehlers), @matplo (Mateusz Ploskon), @loizides (Constantinos Loizides), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @vkucera (Vit Kucera), @davidrohr (David Rohr), @mfasDa (Markus Fasel), @lcunquei (Leticia Cunqueiro Mendez), @adriansev (Adrian Sevcenco), @shahor02 (Ruben Shahoyan), @qgp (Jochen Klein)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/18869) and comment at the bottom of the page.**_

2021-11-11 11:08 UTC, raymondEhlers commented
+1

2021-11-11 11:08 UTC, alibuild commented
2c012ba920effc67d7cd55fb288bb86851db2862: approved: will be automatically merged on successful tests

2021-11-11 12:04 UTC, merged