PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum - Addding pT differential delta-pT histogram
alisw/AliPhysics pull request #22479
Opened 2023-07-08 22:09 UTC by aschmier

PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum - Addding pT differential delta-pT histogram

2023-07-08 22:09 UTC, alibuild commented
73f970c7c8f3bf642f1aed7b201656882092011b: approval required: 1 of @adriansev (Adrian Sevcenco), @chiarazampolli (Chiara Zampolli), @davidrohr (David Rohr), @germainma (Marie Germain), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @ktf (Giulio Eulisse), @lcunquei (Leticia Cunqueiro Mendez), @loizides (Constantinos Loizides), @matplo (Mateusz Ploskon), @mfasDa (Markus Fasel), @pzhristov (Peter Hristov), @qgp (Jochen Klein), @raymondEhlers (Raymond James Ehlers), @sawenzel (Sandro Christian Wenzel), @shahor02 (Ruben Shahoyan), @vkucera (Vit Kucera)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/22479) and comment at the bottom of the page.**_

2023-07-10 15:08 UTC, alibuild commented
0b6d04f9ace8fcc4551edbe0ad82403e9c463ba3: approval required: 1 of @adriansev (Adrian Sevcenco), @chiarazampolli (Chiara Zampolli), @davidrohr (David Rohr), @germainma (Marie Germain), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @ktf (Giulio Eulisse), @lcunquei (Leticia Cunqueiro Mendez), @loizides (Constantinos Loizides), @matplo (Mateusz Ploskon), @mfasDa (Markus Fasel), @pzhristov (Peter Hristov), @qgp (Jochen Klein), @raymondEhlers (Raymond James Ehlers), @sawenzel (Sandro Christian Wenzel), @shahor02 (Ruben Shahoyan), @vkucera (Vit Kucera)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/22479) and comment at the bottom of the page.**_

2023-07-12 14:10 UTC, mfasDa requested changes
I think the histogram type is mixed up, otherwise fine.

2023-07-12 14:10 UTC, mfasDa commented on PWGJE/EMCALJetTasks/Tracks/AliAnalysisTaskEmcalJetEnergySpectrum.cxx
> +        fHistos->FillTH2("hPtJetVsRhoVsDeltaPtRC", ptjet, randomConePt, datajets->GetRhoVal());
Must be `FillTH3`, as the histogram is defined as 3D histogram.

2023-07-12 14:39 UTC, alibuild commented
3d1b625dc5a8bb89df568ff747886214114b5a65: approval required: 1 of @adriansev (Adrian Sevcenco), @chiarazampolli (Chiara Zampolli), @davidrohr (David Rohr), @germainma (Marie Germain), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @ktf (Giulio Eulisse), @lcunquei (Leticia Cunqueiro Mendez), @loizides (Constantinos Loizides), @matplo (Mateusz Ploskon), @mfasDa (Markus Fasel), @pzhristov (Peter Hristov), @qgp (Jochen Klein), @raymondEhlers (Raymond James Ehlers), @sawenzel (Sandro Christian Wenzel), @shahor02 (Ruben Shahoyan), @vkucera (Vit Kucera)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/22479) and comment at the bottom of the page.**_

2023-07-12 14:44 UTC, aschmier commented
I fixed the mix-up, but I may not have squash-merged correctly.

2023-07-12 15:53 UTC, mfasDa commented
Indeed commits are not squashed. Please do so locally and push again as I cannot do it from the webinterface for AliPhysics (for O2-related projects it is possible to squash there)

2023-07-12 17:14 UTC, alibuild commented
b81692a5f9767682cc8bf9a9bd181bf6e2efde33: approval required: 1 of @adriansev (Adrian Sevcenco), @chiarazampolli (Chiara Zampolli), @davidrohr (David Rohr), @germainma (Marie Germain), @jgrosseo (Jan Fiete Grosse-Oetringhaus), @ktf (Giulio Eulisse), @lcunquei (Leticia Cunqueiro Mendez), @loizides (Constantinos Loizides), @matplo (Mateusz Ploskon), @mfasDa (Markus Fasel), @pzhristov (Peter Hristov), @qgp (Jochen Klein), @raymondEhlers (Raymond James Ehlers), @sawenzel (Sandro Christian Wenzel), @shahor02 (Ruben Shahoyan), @vkucera (Vit Kucera)

_Comment with `+1` to approve and allow automatic merging,or with `+test` to run tests only. **Please comment on the pull request: [click here](https://github.com/alisw/AliPhysics/pull/22479) and comment at the bottom of the page.**_

2023-07-12 17:14 UTC, aschmier commented
Okay, should be good now

2023-07-12 17:30 UTC, mfasDa commented
+1

2023-07-12 17:32 UTC, alibuild commented
Error while checking build/AliPhysics/root6 for b81692a5f9767682cc8bf9a9bd181bf6e2efde33 at 2023-07-12 19:32:
```
No log files found
```
Full log [here](https://ali-ci.cern.ch/alice-build-logs/alisw/AliPhysics/22479/b81692a5f9767682cc8bf9a9bd181bf6e2efde33/build_AliPhysics_root6/pretty.html).

2023-07-12 19:16 UTC, merged